server:
    port: 8080

spring.profiles.active: development

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL

---

spring:
    profiles: development
---

spring:
    profiles: production