server:
    port: 8443
    ssl:
        key-store-type: PKCS12
        key-store: classpath:keystore.p12
        key-store-password: 11235813
        key-alias: localhost

security:
    require-ssl: true

spring:
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        show-sql: true
    queries:
        users-query: select email, password, TRUE from app_user where email=?
        authorities-query: SELECT email, 'ROLE_USER' FROM app_user WHERE email=?
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: ${sql_host}
        username: ${sql_username}
        password: ${sql_password}

facebook:
    app-id: ${facebook_id}
    app-secret: ${facebook_secret}
twitter:
    app-id: ${twitter_id}
    app-secret: ${twitter_secret}
google:
    app-id: ${google_id}
    app-secret: ${google_secret}
    api-key: ${google_api_key}

jwt-secret: ${jwt_secret}

application.URL: ${frontend}

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL