server:
    port: 8443
#    ssl:
#        key-store-type: PKCS12
#        key-store: classpath:dev.p12
#        key-store-password: 11235813
#        key-alias: ${key_alias}

#security:
#    require-ssl: false

spring:
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: ${sql_host}
        username: ${sql_username}
        password: ${sql_password}

facebook:
    app-id: ${facebook_id}
    app-secret: ${facebook_secret}
twitter:
    app-id: ${twitter_id}
    app-secret: ${twitter_secret}
google:
    app-id: ${google_id}
    app-secret: ${google_secret}
    api-key: ${google_api_key}

jwt-secret: ${jwt_secret}

application.URL: ${frontend}

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL
